### ISSUE TITLE
Inaccurate detection

### ISSUE THREAD

**Issue by lishishuang1992** [edrosten/fast-C-src#1]
hi Edward Rosten:
      When I run the code on the iOS device,Point of detection is not accurate.What needs to be done.
      Look forward to your reply！
      Thank you.
      Good luck.

**Comment by edrosten** [comment]
On 17 February 2017 at 02:58, 李世爽 <notifications@github.com> wrote:

> hi Edward Rosten:
> When I run the code on the iOS device,Point of detection is not
> accurate.What needs to be done.
>

There's not a lot of information to go on here. Can you give me any more
details?

**Comment by lishishuang1992** [comment]
hi Edward Rosten:
   Thank you, I have solved this problem, before I was introduced to the original image value, and then the gray pixel value. Very accurate detection.
Thank you.
Good luck！

**Comment by lishishuang1992** [comment]
I thought that 'data' was origin stream of image, until I transfer it to pixel array.Thank you for your fastest C
