### ISSUE TITLE
How to match these corners and track them ?

### ISSUE THREAD

**Issue by pritasam** [edrosten/fast-C-src#2]
Hi,

Thanks for this awesome library...I am using image sequences through camera and based on corners detected in the first image I am trying to track those corners in the other images ?

Do you think the BFMatcher in the opencv will help ? or do you know any other way which can help tracking the corners ?

**Comment by edrosten** [comment]
Depends on your application, really. BFMatcher likely will work but that'll depend on the features and it'll probably be pretty slow.
